version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${BACKEND_PORT}:8000"
    networks:
      - mynetwork
    entrypoint: [
      "uvicorn", 
      "app.main:app", 
      "--host", "0.0.0.0", 
      "--port", "8000"
    ]

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
